# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hladeiro <hladeiro@student.42lisboa.com>   +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/05/18 20:04:32 by hladeiro          #+#    #+#              #
#    Updated: 2025/05/18 20:07:41 by hladeiro         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = interface
CXX = c++
FLAGS = -Wall -Wextra -Werror -std=c++98
SRC = AMateria.cpp Character.cpp
OBJ =
